[package]
name = "ribbit"
version = "0.1.0"
authors = ["Jae Anne Bach Hardie <jabh@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
